### ISSUE TITLE
Is this Repo related to any paper?

### ISSUE THREAD

**Issue by RizhaoCai** [NunuM/where-am-i-android-app#2]
Is this Repo related to any papers? If yes, what papers are they?

**Comment by NunuM** [comment]
@RizhaoCai No, thare is no direct paper. This work was done in my spare time, following one research that I have done for a class in the University about Wi-Fi Fingerprinting (second post, when you open the app). Just for curiosity, why do you ask?

If you need some feature or something useful, you can ask me.

**Comment by RizhaoCai** [comment]
> @RizhaoCai No, thare is no direct paper. This work was done in my spare time, following one research that I have done for a class in the University about Wi-Fi Fingerprinting (second post, when you open the app). Just for curiosity, why do you ask?
> 
> If you need some feature or something useful, you can ask me.

Because I am recently studying WiFi applications and wish to learn the principle (i.e. how it works).
Thanks.
